# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
	git
	zsh-autosuggestions
	zsh-syntax-highlighting
	)


source $ZSH/oh-my-zsh.sh

# Robbyrussell uses %c (current folder name only). Show full path (~ for $HOME).
PROMPT="%(?:%{$fg_bold[green]%}%1{➜%} :%{$fg_bold[red]%}%1{➜%} ) %{$fg[cyan]%}%~%{$reset_color%}"
PROMPT+=' $(git_prompt_info)'

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
 export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias lt="ls -ltr"


# Host banner + rainbow welcome (interactive shells only)
_omz_welcome_banner() {
  [[ -o interactive ]] || return 0

  local host user os kernel arch up load mem disk ip env_line
  host=$(hostname 2>/dev/null || echo '?')
  user=${USER:-$(id -un)}
  if [[ -r /etc/os-release ]]; then
    os=$(grep -E '^PRETTY_NAME=' /etc/os-release | cut -d= -f2- | tr -d '"')
  else
    os=$(uname -s 2>/dev/null || echo '?')
  fi
  kernel=$(uname -r)
  arch=$(uname -m)
  up=$(uptime -p 2>/dev/null)
  [[ -z $up ]] && up=$(awk '{d=int($1/86400); h=int(($1%86400)/3600); if(d>0) printf "%dd %dh", d, h; else if(h>0) printf "%dh", h; else printf "%dm", int($1/60)}' /proc/uptime 2>/dev/null)
  [[ -z $up ]] && up="n/a"
  load=$(awk '{printf "%s  %s  %s", $1, $2, $3}' /proc/loadavg 2>/dev/null)
  [[ -z $load ]] && load="n/a"
  mem=$(free -h 2>/dev/null | awk '/^Mem:/ {print $3 " / " $2 " (avail " $7 ")"}')
  [[ -z $mem ]] && mem="n/a"
  disk=$(df -h / 2>/dev/null | awk 'NR==2 {print $3 " / " $2 " (" $5 " full)"}')
  [[ -z $disk ]] && disk="n/a"
  ip=$(hostname -I 2>/dev/null | awk '{print $1; exit}')
  [[ -z $ip ]] && ip="n/a"
  if grep -qi microsoft /proc/version 2>/dev/null; then
    env_line="WSL"
  else
    env_line=$(uname -s)
  fi

  local banner_title
  local -a _parts
  _parts=()
  if grep -qi microsoft /proc/version 2>/dev/null; then
    _parts+=(WSL)
  elif [[ -f /.dockerenv ]] || { [[ -r /proc/1/cgroup ]] && grep -qE '(docker|podman|containerd|kubepods|lxc)' /proc/1/cgroup 2>/dev/null; }; then
    _parts+=(container)
  elif command -v systemd-detect-virt >/dev/null 2>&1; then
    local _virt
    _virt=$(systemd-detect-virt 2>/dev/null)
    if [[ -z $_virt || $_virt == none ]]; then
      _parts+=(physical)
    else
      _parts+=("$_virt")
    fi
  else
    _parts+=(system)
  fi
  [[ -n $SSH_CONNECTION ]] && _parts+=(SSH)
  banner_title="${(j: · :)_parts} · snapshot"

  clear
  local B='\e[38;5;38m' L='\e[38;5;246m' V='\e[38;5;252m' Z='\e[0m'

  printf '\n'
  printf '%b────────────────────────────────────────────────────────────────%b\n' "$B" "$Z"
  printf '%b  %s%b\n' "$V" "$banner_title"
  printf '%b────────────────────────────────────────────────────────────────%b\n' "$B" "$Z"
  printf '%b  %-14s%b %s\n' "$L" "Host" "$Z" "$host"
  printf '%b  %-14s%b %s @ %s\n' "$L" "User" "$Z" "$user" "$host"
  printf '%b  %-14s%b %s\n' "$L" "Environment" "$Z" "$env_line"
  printf '%b  %-14s%b %s\n' "$L" "OS" "$Z" "$os"
  printf '%b  %-14s%b %s (%s)\n' "$L" "Kernel" "$Z" "$kernel" "$arch"
  printf '%b  %-14s%b %s\n' "$L" "Uptime" "$Z" "$up"
  printf '%b  %-14s%b %s\n' "$L" "Load avg" "$Z" "$load"
  printf '%b  %-14s%b %s\n' "$L" "Memory" "$Z" "$mem"
  printf '%b  %-14s%b %s\n' "$L" "Disk (/) " "$Z" "$disk"
  printf '%b  %-14s%b %s\n' "$L" "IPv4" "$Z" "$ip"
  printf '%b────────────────────────────────────────────────────────────────%b\n' "$B" "$Z"

  local text='Welcome to my Friend!!!'
  local i idx
  local colors=(
    196 202 208 214 220 226 190 154 118 82 46 47 48 49 51 45 39 33 27
    63 69 75 81 87 93 99 105 111 117 123 129 135 141 147 153 159 165 171
  )
  local n=${#colors}
  printf '\n'
  for (( i=1; i<=${#text}; i++ )); do
    idx=$(( (i - 1) % n + 1 ))
    printf '\e[38;5;%sm%s' "${colors[idx]}" "${text[i]}"
  done
  printf '\e[0m\n\n'
}
_omz_welcome_banner
unset -f _omz_welcome_banner

